spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/simple_task?serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      repositories:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus