spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/simple_task?serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  session:
    redis:
      save-mode: on_set_attribute
      flush-mode: on_save
      namespace: simpletask:session
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
server:
  servlet:
    session:
      timeout: 24h
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus